name: Web Site Bot Testi

on:
  workflow_dispatch: # Manuel başlatma butonu için

jobs:
  run-bot:
    # Tekrar en güncel ve kararlı imaja dönüyoruz
    runs-on: ubuntu-latest

    steps:
    - name: Kodlari Klonla
      uses: actions/checkout@v4

    - name: Python Kurulumu
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Gerekli Kutuphaneleri Yukle
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        # İşte sihirli dokunuş: --force parametresi ile apt paket hatalarını bypass ediyoruz
        playwright install chromium --with-deps --force

    - name: Botu Calistir
      run: python bot.py "https://furkantoprakhairstudio.github.io/goruntulenme/"
